### ISSUE TITLE
[css-masking] Change percentage value of clip-path

### ISSUE THREAD

**Issue by lahmatiy** [w3c/fxtf-drafts#168] opened 2017-05-18 22:43 UTC
Current value of `clip-path` percentage is `as specified`. It's confusing. I think it should be something like `refer to reference box when specified, otherwise border-box`.

**Comment by AmeliaBR** [comment] 2017-05-18 23:22
Duplicate of #155.  You can add comments there.  

It definitely looks like a copy & paste error to me. "As specified" makes no sense in that context.

**Closed by AmeliaBR** 2017-05-18 23:22 UTC

**Comment by lahmatiy** [comment] 2017-05-18 23:27
My bad. I don't know how I missed my own issue about the problem 😊 
Thank you for your comment.

**Comment by AmeliaBR** [comment] 2017-05-19 16:53
Oh, goodness. I didn't even notice that it was the same person posting both issues! I'm clearly not the only one who has been spending too much time this week examining the dark corners of the masking & clipping specs.

**Comment by lahmatiy** [comment] 2017-05-19 17:05
I'm working on JSON schema for MDN data (https://github.com/mdn/data/pull/71), as a result I found this problem.
