### ISSUE TITLE
[filter-effects] SVGFEConvolveMatrixElement misses property for preserveAlpha attribute

### ISSUE THREAD

**Issue by SebastianZ** [w3c/fxtf-drafts#138] opened 2017-04-29 16:53 UTC
The [`SVGFEConvolveMatrixElement` interface definition](https://drafts.fxtf.org/filters/#InterfaceSVGFEConvolveMatrixElement) misses a property corresponding to the [`preserveAlpha` attribute of the `<feConvolveMatrix>` element](https://drafts.fxtf.org/filters/#element-attrdef-feconvolvematrix-preservealpha).

SVG 1.1 has a [`preserveAlpha` property](https://www.w3.org/TR/SVG/filters.html#__svg__SVGFEConvolveMatrixElement__preserveAlpha) for this purpose.

Sebastian

**Comment by AmeliaBR** [comment] 2017-04-29 19:23
Duplicate of https://github.com/w3c/fxtf-drafts/issues/114, Restore SVGFEConvolveMatrixElement#preserveAlpha IDL attribute

See discussion on that issue about why it was removed, and why it would probably be easier to put it back.

**Closed by AmeliaBR** 2017-04-29 19:23 UTC

**Comment by SebastianZ** [comment] 2017-04-30 09:44
Ah, right. Sorry that I missed that issue and thanks for the note, Amelia!

Sebastian
