### ISSUE TITLE
filter should be defined to establish a containing block for fixed and absolutely positioned elements

### ISSUE THREAD

**Issue by dbaron** [w3c/fxtf-drafts#11] opened 2016-06-27 23:26 UTC
As resolved in http://www.w3.org/2015/02/10-fx-minutes.html#action02 and mentioned in the introduction to the spec, 'filter' not 'none' should create a containing block for absolutely and fixed positioned elements.

(Per https://lists.w3.org/Archives/Public/public-fx/2015OctDec/0035.html I think we should explicitly state that it also applies to absolutely positioned elements, and not just assume the reader can infer that absolute implies fixed as well, since nothing says that.)

**Comment by dholbert** [comment] 2016-10-18 20:00
CC @erikdahlstrom @dirkschulze can we get this addressed?

**Comment by chrishtr** [comment] 2016-11-02 18:04
I'm concerned that this will make it impossible to apply a filter (e.g., for accessibility to change the color) to an entire webpage without messing up fixed-position elements. This is because there is no HTML
element exposed to the developer which is the containing block for fixed-position elements.

**Comment by mstange** [comment] 2016-11-02 18:13
That is true and a bit unfortunate.

In browsers that support `backdrop-filter`, you can put a fixed element on top of everything (with `pointer-events: none`) and apply the filter you want as that element's backdrop filter. But that's more a workaround than a true solution.

A better solution would be the ability to set the filter directly on the containing block for fixe-position elements. I don't know how you would expose that.

**Comment by richschwer** [comment] 2016-11-02 19:20
I may have misunderstood your comment, but, aria-hidden only hides the container and its descendants from an AT (screen reader/screen magnifier, etc.) and it does not impact the visibility of the element or its descendants.
 
Rich Schwerdtfeger
 
 
----- Original message -----From: chrishtr <notifications@github.com>To: w3c/fxtf-drafts <fxtf-drafts@noreply.github.com>Cc:Subject: Re: [w3c/fxtf-drafts] filter should be defined to establish a containing block for fixed and absolutely positioned elements (#11)Date: Wed, Nov 2, 2016 1:04 PM 
I'm concerned that this will make it impossible to apply a filter (e.g., for accessibility to change the color) to an entire webpage without messing up fixed-position elements. This is because there is no HTMLelement exposed to the developer which is the containing block for fixed-position elements.

**Comment by chrishtr** [comment] 2016-11-14 19:24
My comment was not about aria. It was about losing the ability to provide a color or other filter extension
for web pages, without causing the page to display fixed-position elements incorrectly.

**Comment by mstange** [comment] 2016-11-14 19:32
The only other idea I have for addressing that case is: We could make `filter` on the root element special, similar to what we do for `overflow` and `background`, and make it always propagate up to the containing block for position:fixed elements.

**Comment by bzbarsky** [comment] 2017-04-03 16:38
@dirkschulze @erikdahlstrom any chance of this spec getting updated per the resolution mentioned above?

**Comment by chrishtr** [comment] 2017-04-04 22:27
If there is consensus, I'd like to try to make this change in Chrome.

**Comment by bzbarsky** [comment] 2017-04-05 03:27
Note that Firefox has been shipping this behavior for a while now, as I understand, since that was what the working group resolved...

**Comment by mstange** [comment] 2017-11-08 02:46
@dbaron, can you clarify the resolution? If you set a blur filter on the root element, should fixpos elements be blurred?

**Comment by mstange** [comment] 2017-11-08 02:57
Also, when I have an SVG filter applied to the root element which draws a green square at 100,100 using `<feFlood flood-color="lime" x="100" y="100" width="100" height="100"/>`, should scrolling move the square? (The solution I proposed in https://github.com/w3c/fxtf-drafts/issues/11#issuecomment-260437470 would not move the square.)

If the root element has a transparent background, should a filter on the root element apply to the default background color? (The default background color usually gets rendered behind the root stacking context; for example, `mix-blend-mode` blending does not blend with the default background color.)

**Comment by chrishtr** [comment] 2017-11-08 18:36
It's also not so clear to me what "root element" means. Is that the <html> element?

**Comment by dholbert** [comment] 2017-11-08 22:12
For an HTML document, yes -- but the behavior in question (that we'd be mimicking here for filters) also involves the `<body>` element and the viewport.  Here's the spec text for the behaviors that Markus was referencing for `overflow` and `background`, with more concrete definitions/explanations:
https://www.w3.org/TR/css-overflow-3/#overflow-propagation
https://www.w3.org/TR/css-backgrounds-3/#body-background

**Comment by upsuper** [comment] 2017-11-11 00:01
I think the resolution was that, when a `filter` is applied to `body` (or the `documentElement`? This is one place which confused me in the meeting), the filter is instead applied to the viewport (so that fixed-pos elements would continue being fixed-pos rather than becoming absolutely-pos).

**Comment by dbaron** [comment] 2017-11-30 00:50
I think the idea is that a `filter` on the root element (and *maybe* also the `body`) would:
* not change any containing blocks
* set the filter on the canvas rather than the root element's box (or `body`'s box, if applied to `body` as well)

This would apply that `position: fixed` elements would be filtered by a filter on the root, but they'd also still be fixed rather than behaving like absolute as other `position: fixed` elements with an ancestor with `filter` would.

It's probably worth checking with some others with the discussion that they agree that was the intent.

**Comment by dbaron** [comment] 2017-11-30 00:52
And I think it wouldn't filter the default background color, since if the document is transparent, then that default background color lives behind the document.  But I'm not sure that concept is specified clearly.

**Comment by mstange** [comment] 2017-12-06 21:32
I see, so the filter should be applied to the canvas, not to the viewport. Applying it on the canvas means that:

 1. Scrolling the document will scroll the filter. This only makes a difference for filters that have position-dependent rendering, like `<feFlood flood-color="lime" x="100" y="100" width="100" height="100"/>`.
 2. The scrollbars for the root scroll frame are not filtered. They exist outside the filter.
 3. The root scroll frame's "scrollport clip" (i.e. the viewport minus scrollbars) applies to the filtered results, not to the contents of the filter.

I'm happy with this proposal. @chrishtr, what do you think?

**Comment by chrishtr** [comment] 2017-12-14 01:00
That is fine with me too. Sorry for the delay.

**Comment by dirkschulze** [comment] 2017-12-15 15:51
@mstange @dbaron @chrishtr @dholbert @bzbarsky To summarize: The CSS WG resolution stands: filters should establish containing blocks for abspos and fixpos with the exception of the root element (outermost root element in SVG terms).

The viewport is defined as a region and is no content itself nor does it describe a surface. The canvas is a (theoretically) infinite (unbound) drawing surface. We never filter regions but filters or filtered content might get clipped to regions. So I am not sure if the specification actually needs to differ between the filtered "canvas" or filtered "viewport".
In fact, I am not sure if we even need to reference the term "canvas". IMO all that is needed is the exception for: "The outermost document root element in the current document context."
* I am not sure if HTML/CSS has a term for "root" element that applies to SVG as well.
* document context is meant for embedded documents with `<foreignObject>`, `<object>`/`<embed>`, `<frame>` where the document root element is "within" those elements.

I welcome better prose proposal. :)

**Comment by dirkschulze** [comment] 2017-12-28 19:32
I added the requested change right below the filter property definition: https://drafts.fxtf.org/filter-effects-1/#FilterProperty

Please review the change and re-open this issue if it is not satisfying.

**Comment by isiahmeadows** [comment] 2018-01-06 01:44
@dirkschulze So what does that make of [this Mozilla bug (that I filed thinking it was a program bug)](https://bugzilla.mozilla.org/show_bug.cgi?id=1426919)?

**Comment by dirkschulze** [comment] 2018-01-06 08:31
@isiahmeadows Filters create a containing block for descendants now. This means, the behavior of Firefox is following the spec with the edits from https://github.com/w3c/fxtf-drafts/commit/4081edacf7bc550a7391447504a16cc10136134c . The `filter` behaves like `transform` now.

I should probably modify this sentence as clarification:
> Any value other than `none` for the `filter` property causes the element to become a containing block, and the object acts as a containing block for fixed positioned descendants.

Just for completeness: `filter` also create a stacking context. The spec states that a couple paragraphs later.

**Comment by isiahmeadows** [comment] 2018-01-06 08:49
@dirkschulze So, is there a way to access an element that's the global stacking context root? (As in, is `:root` it, or is it something else?)

**Comment by isiahmeadows** [comment] 2018-01-06 08:49
Note: this is relevant for any "night mode" extension writers, who generally work by applying a `filter` to the page.

**Comment by dirkschulze** [comment] 2018-01-06 09:22
@isiahmeadows As I understood the resolution (and it was changed in the spec to) it would be `:root`.

**Comment by chrishtr** [comment] 2018-01-24 19:10
@dbaron @mstange @dirkschulze 
Update: Blink is now implementing the change.

Unfortunaley I don't think the resolution described in comments on Nov 29 and Dec 6 (and reflected in the draft spec) are what is desired. I didn't read it carefully enough at the time, sorry about that. :(

From that resolution, one would conclude that root element that is filtered is not a containing block for any fixed-position elements. This is at odds with what I see as the core intent of the whole change, which
is to not have any element ever have a containing block chain which skips an ancestor filter.

Instead, the filter should apply to the viewport (in Blink/WebKit-speak, the LayoutView). Thus:

1. The filter does *not* scroll with the content
2. It is a containing block for every descendant, including fixed-position elements
3. It applies to the clipped contents of the viewport
4. It filters the root background color (perhaps this is optional though, if there are use-cases where it is really not desired)
5. It does not apply to scrollbars (same as previous resolution)

In terms of order of conceptual operations for drawing the content to the screen, it would be:

a. Draw content under root scroll
b. Scroll (a)
c. Draw fixed-position content (not technically accurate here because of z-index, but anyway..)
c. Clip to viewport
d. Apply filter
e. Draw scrollbars

**Comment by chrishtr** [comment] 2018-01-24 19:59
Also, the current level 1 filter spec says that scrollbars of overflow-scroll elements should be filtered:

"Conceptually, any parts of the drawing are effected by filter operations. This includes any content, background, borders, text decoration, outline and visible scrolling mechanism of the element to which the filter is applied"

https://www.w3.org/TR/filter-effects-1/#FilterProperty

I can see how this is desirable, since developers may want to gray out a scroller when it is inactive
in the current view.

However, the root scrollbar of the webpage is special and should I think be considered something
under the control of the user agent, for accessibility reasons.

**Comment by mstange** [comment] 2018-01-24 21:25
I prefer your new proposal over what we decided on previously.

**Comment by dirkschulze** [comment] 2018-01-25 02:43
@chrishtr We are still talking about a filter applied to the root element and not to arbitrary elements? Asking specifically because of your "Clip to viewport" rule.

**Comment by chrishtr** [comment] 2018-01-25 03:23
Yes, just adjustment for root element.

**Comment by chrishtr** [comment] 2018-03-08 19:42
PR for this change:

https://github.com/w3c/fxtf-drafts/pull/263

**Comment by chrishtr** [comment] 2018-04-11 17:03
Ping on this. Does the PR look ok? it's a one-sentence edit.

**Comment by dirkschulze** [comment] 2018-04-11 19:46
@chrishtr Thanks for the PR. I'll put this on the agenda of the CSS WG.

**Comment by vmpstr** [comment] 2018-04-26 20:37
Just as clarification, our interpretation of the latest draft (including #263 ) is the following:
- Non-none filter value establishes a containing block for elements.
- The exception to this is the document element. In other words if the document element is filtered, the filter is applied after scroll and clip but before viewport scrollbars. This logic applies to all frames, including iframes.

This means that:
1. body is not treated any differently from any other non-document-element element.*
2. fixed position children of filtered document element do not scroll (ie, the same behavior as if the document element was not filtered).

* - @chrishtr and I discussed this and we believe that this is good behavior, which avoids a quirk in which document element "steals" body's filter.

**Comment by mstange** [comment] 2018-04-26 20:43
That sounds correct to me, yes.

**Comment by dirkschulze** [comment] 2018-04-27 08:51
@chrishtr Could you clarify?
> This logic applies to all frames, including iframes.

It sounded like in your description, scrollbars should still get filtered for iframes, just not for the actual window scrollbars. Did I misunderstand this aspect?

**Comment by astearns** [comment] 2018-06-18 23:48
@christr @dirkschulze Did the discussion on issue #282 last week cover this? https://github.com/w3c/fxtf-drafts/issues/282#issuecomment-397007286

Or do we still need to go over the PR for this issue?

**Comment by chrishtr** [comment] 2018-06-19 00:28
We still need to go over this issue. It's different than the other one.

**Comment by atanassov** [comment] 2018-08-20 18:31
The issue is not ready for CSSWG discussion since we're waiting for use cases (as discussed on last call, see minutes above).

**Comment by chrishtr** [comment] 2018-09-06 03:32
I'm going to close this issue in favor of #282. Going to post a complete proposed solution to all issues on that issue.

**Closed by chrishtr** 2018-09-06 03:32 UTC
Labels: Needs CSSWG Input/Decision, filter-effects-1

**Comment by Lonniebiz** [comment] 2020-07-04 02:30
The spec need to make exception for filters that have nothing to do with size or positioning (color-based filters for example).

If I want to grayscale the entire page, why should that have any effect on absolute/fixed positioned descendants?

Take a look at this example:
https://stackoverflow.com/questions/62717289/

There, I'm trying to grayscale an entire webpage that contains a fixed positioned element. As soon as I apply the filter, it breaks the positioning (no longer allowing me to fix that element to the "Dead Center" of the page).

Shouldn't the type of filter be taking into consideration instead just assuming that all filters must sabotage fixed/absolute positioning? If a particular filter has nothing to do with size/positioning, then no descendants should be encapsulated with a container-elements.

I'm very disappointed that the spec doesn't provide any granularity: all filters corrupt fix/absolute descendants, while that behavior should only be reserved for those certain filter-types that really can't work without that treatment.

A filter that only effects color, shouldn't bother descendant's position in any way!

**Comment by chrishtr** [comment] 2020-07-05 05:09
[The spec says](https://drafts.fxtf.org/filter-effects-1/#FilterProperty) that a filter on the HTML element does not break fixed position elements. In particular:

```A value other than none for the filter property results in the creation of a containing block for absolute and fixed positioned descendants unless the element it applies to is a document root element in the current browsing context.```

This behavior is implemented in at least Chromium and works correctly on this page (just tried it). This exception for the root element was made for the use case you described about fixed-position elements.

**Comment by Lonniebiz** [comment] 2020-07-05 15:01
@chrishtr Those containing blocks do indeed break fixed/absolute positioned descendants and the root element exception that's working in Chromium, and [not in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1650522), is not enough in my opinion.

On filters that modify color, and have no aspiration of modifying size or position, the containing blocks should not be created even if the target element is NOT root. I've submitted a separate issue [here](https://github.com/w3c/fxtf-drafts/issues/402). The spec should impose the granularity of making the containing blocks conditional based on the type(s) of filters being applied and not just the non-granular all filters approach. Color related filters like `grayscale` and `invert` should not invoke the creation of containing blocks (even when applied to non-root elements).

For example, `body { filter: grayscale(100%); }`, should not cause the creation of containing blocks, even though the filter is being placed on `body` instead of `:root`. This should be the case on any element. https://github.com/w3c/fxtf-drafts/issues/402

**Comment by chrishtr** [comment] 2020-07-05 21:44
> @chrishtr Those containing blocks do indeed break fixed/absolute positioned descendants and the root element exception that's working in Chromium, and [not in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1650522), is not enough in my opinion.

The situation with Firefox (and Webkit most likely) it is just a browser bug that should be fixed.

> On filters that modify color, and have no aspiration of modifying size or position, the containing blocks should not be created even if the target element is NOT root. I've submitted a separate issue [here](https://github.com/w3c/fxtf-drafts/issues/402). The spec should impose the granularity of making the containing blocks conditional based on the type(s) of filters being applied and not just the non-granular all filters approach. Color related filters like `grayscale` and `invert` should not invoke the creation of containing blocks (even when applied to non-root elements).

It's not just size and position. Even filters that don't affect such things would have ill-defined behavior for non-contained elements, and make it significantly more difficult to implement hardware-accelerated rendering paths.

**Comment by emilio** [comment] 2020-08-26 12:33
We should update the spec to reflect https://github.com/w3c/fxtf-drafts/issues/11#issuecomment-360240933 I suspect. Blink and WebKit do filter the whole viewport.

**Comment by chrishtr** [comment] 2020-08-26 17:08
@emilio: Do you mean the comment about the containing block thing not apply to the root element?

**Comment by emilio** [comment] 2020-08-26 17:35
The only reference to this special case I see in [the spec](https://drafts.fxtf.org/filter-effects/) is:

> A value other than none for the filter property results in the creation of a containing block for absolute and fixed positioned descendants unless the element it applies to is a document root element in the current browsing context. The list of functions are applied in the order provided.

Which is not quite only what's going on. The actual behavior is a lot more subtle, as you need to also "lift" the filters from the root element box to the viewport (minus scrollbars), so that they apply to fixed pos elements, etc.

**Comment by chrishtr** [comment] 2020-08-26 17:42
> Which is not quite only what's going on. The actual behavior is a lot more subtle, as you need to also "lift" the filters from the root element box to the viewport (minus scrollbars), so that they apply to fixed pos elements, etc.

Oh, that part. I did add that to the compositing spec in [this PR](https://github.com/w3c/fxtf-drafts/pull/385/files).
