### ISSUE TITLE
[filter-effects-1] What is the visual effect of filter() on the document element?

### ISSUE THREAD

**Issue by smfr** [w3c/fxtf-drafts#282] opened 2018-04-28 19:09 UTC
WebKit and other browsers disagree about the visual rendering of filter() on the document root element:

`html {
    filter: invert(1);
    background-color: blue;
}`

[https://codepen.io/smfr/pen/LmxZZP](https://codepen.io/smfr/pen/LmxZZP)

Safari renders white text on yellow, Blink/Firefox render white text on blue.

Should the root background be affected by the filter()? I would expect yes, making WebKit behavior correct.

**Comment by smfr** [comment] 2018-04-28 19:15
Also need to consider:
`html {
    filter: invert(1);
    background-color: transparent;
}`

Is the filter applied before or after the UA renders its default view background color?

**Comment by AmeliaBR** [comment] 2018-04-28 20:40
I would expect a filter on the root element to affect the canvas, just like a transform on the root element is expected to affect the background canvas.

[From the transforms spec](https://drafts.csswg.org/css-transforms/#transform-rendering) (end of the linked section):

> Note: If the root element is transformed, the transformation applies to the entire canvas, including any background specified for the root element. Since the background painting area for the root element is the entire canvas, which is infinite, the transformation might cause parts of the background that were originally off-screen to appear. For example, if the root element’s background were repeating dots, and a transformation of scale(0.5) were specified on the root element, the dots would shrink to half their size, but there will be twice as many, so they still cover the whole viewport.

**However,** a [modified version of your test](https://codepen.io/AmeliaBR/pen/JvERRb/) shows that browsers don't actually implement that part of the Transforms spec: WebKit and Chrome transform the background, but don't fill in extra background image repeats, while Firefox and Edge don't transform the root background at all.

So, for implementers, these should probably be fixed together. But in both cases, we probably need spec clarifications, and actual normative text (not just the informative note from Transforms).


_____________________

Aside: For authors, a workaround that should work for now is to put the background on the `<body>` element, give the body a min-height of 100vh (minus margins), and then give the root element a solid background color to prevent hoisting of the body background to the canvas.

**Comment by mstange** [comment] 2018-04-29 00:50
As per https://github.com/w3c/fxtf-drafts/issues/11#issuecomment-360240933 the filter *should* apply to the document element's background color. However, that comment does not mention how the default background color should be treated. For consistency with `mix-blend-mode` I would suggest that the default background color *not* be filtered. This would also make sense for the case where there is a specified opaque background color on the `html` or `body` element but the filter turns it transparent; then the default background color should be visible behind the filter.

**Comment by dirkschulze** [comment] 2018-04-29 09:06
@smfr that looks like a duplicate of #11 (as @mstange noted as well). Can we close this issue and continue the discussion on the other issue? Note that the other issue is on the agenda of the next CSS WGs meeting.

**Comment by smfr** [comment] 2018-04-29 15:46
I think issue #11 is about containing block side effects. This is about the visual rendering, which is different.

**Comment by tabatkins** [comment] 2018-04-29 19:11
I agree with @mstange - I think the filter should apply to the canvas, but *not* the default backdrop color.

So in the @smfr's first example (`html` element has black text + blue background), it should render as white text on yellow, but in his second example (`html` element has black text and transparent backgrounnd), it should render as white text on transparent, showing the normal backdrop color thru.

**Comment by smfr** [comment] 2018-04-30 04:28
Informal twitter poll here: https://twitter.com/smfr/status/990792916124581888

**Comment by smfr** [comment] 2018-04-30 04:31
Does CSS specify anywhere what the default background is? Is it as if the UA stylesheet had `html { background-color: white }`, or is the default background painting outside of CSS?

**Comment by AmeliaBR** [comment] 2018-04-30 16:57
@smfr

The default background is traditionally customizable (e.g., Firefox lets you set this as a user style).  

[CSS Backgrounds](https://drafts.csswg.org/css-backgrounds/#special-backgrounds) says:

> The document canvas is the infinite surface over which the document is rendered. ... If the canvas background is not opaque, what shows through is UA-dependent.

However, [WHATWG HTML says](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3):

> The initial value for the 'color' property is expected to be black. The initial value for the 'background-color' property is expected to be 'transparent'. The canvas's background is expected to be white.

Elsewhere, [CSS Backgrounds says](https://drafts.csswg.org/css-backgrounds/#root-background) that a background on the root element or HTML body element is propagated to the canvas.  So it is theoretically possible to insist that "the background that shows through from a transparent canvas" is white, while also allowing customization in the form of a `:root {background-color: <user-setting>}` style rule. The difference would be revealed if an author style sets a (semi-)transparent root background: does it override the user setting, or layer on top of it? 

Firefox implements it using the layered approach: the user-defined color is applied underneath any background set on the root element.

**Comment by tabatkins** [comment] 2018-04-30 19:16
There's a difference between "the background that gets propagated to the canvas" (from `html` or `body`) and the underlying backdrop (which is UA-specific and undefined).

If filters on `html` apply to the canvas backdrop, what happens with `html { filter: opacity(50%); }`? What shows thru?  Presumably not whatever window is underneath the browser window. ^_^

Obviously, there's *some* background that isn't affected by the filter, so that you can show something underneath an opacity() filter.  Rather than inventing *yet another* layer to explain this, let's just be consistent with previous resolutions (such as [our resolution that `background-blend-mode` blends with the `html` background, not the canvas backdrop](https://lists.w3.org/Archives/Public/www-style/2014Jun/0380.html).

**Comment by smfr** [comment] 2018-04-30 23:34
Rik points to previous discussion at https://lists.w3.org/Archives/Public/public-fx/2015JanMar/0052.html

**Comment by smfr** [comment] 2018-05-01 00:05
Sadly twitter mostly disagrees with the previous resolution about how filter() on the root works; most people expect `html { filter: invert(); }` to produce a black background, and for the addition of `html { backgroound-color: white; }` to not change that behavior.

**Comment by dirkschulze** [comment] 2018-05-01 04:54
@smfr The thread comes to the same conclusion as @tabatkins’s proposal above and does make sense IMO. I agree with the conclusion that some kind of backdrop is required for compositing which should not be affected by filters either. (Though might be relevant for feBlend of course.)
If we change that, we need to define a default solid backdrop color. We run into the described issue (opacity and so on) and disallow any new UA to actually let the background of the UA shine though. (Not sure if that ever will be desired but who knows in times of AR.)

With defining `background` on the root element there is a way to descibre the desire to invert the background as well for authors.

Though the voting on the Twitter thread might go in another direction, the outcome in the thread makes the most sense IMO.

**Comment by smfr** [comment] 2018-05-05 03:40
Here's another thing with the Firefox/Blink implementation:
`
html { }
body {
    filter: invert(1);
    background-color: white;
}
`
does not result in a black body background, because the body background got propagated to the root. So the content is inverted, but not the background.

Now add a background on the html:
`
html {
    background-color: pink;
 }
body {
    filter: invert(1);
    background-color: white;
}
`
and suddenly the body has a black background. That's terrible for authors.

**Comment by smfr** [comment] 2018-05-05 03:44
So how does the resolution work in the case of:
`html { } body { filter: invert(1); background-color: white; }`
Does the white get propagated to the document element, and thus get considered as "the html background"?

**Comment by mstange** [comment] 2018-05-05 03:54
> So how does the resolution work in the case of:
> `html { } body { filter: invert(1); background-color: white; }`
> Does the white get propagated to the document element, and thus get considered as "the html background"?

It gets propagated to the canvas, and is not affected by filters on the `body` element. But, per the resolution in https://github.com/w3c/fxtf-drafts/issues/11#issuecomment-360240933, it *is* affected by filters on the `html` element.

The behavior in the two previous examples is unfortunate but similar things happen in lots of other circumstances. For example, in `html { } body { margin: 50px; height: 100px; background-color: black; }` the black fill is unaffected by the body's height or margin, but in `html { background-color: pink; } body { margin: 50px; height: 100px; background-color: body; }` the black fill *is* affected by the body's height and the margin.

**Comment by tabatkins** [comment] 2018-05-07 21:04
Yeah, the propagation from `body` is unfortunate, but something we're stuck with. Oh well.

**Comment by LeaVerou** [comment] 2018-05-30 16:23
> @smfr wrote:
> Informal twitter poll here: twitter.com/smfr/status/990792916124581888

Another informal twitter poll with convenient stats: https://twitter.com/LeaVerou/status/1001859421469855744

**Comment by tabatkins** [comment] 2018-05-30 21:06
Again, these sorts of polls aren't particularly useful. This isn't something people have thought about before, so you're just getting a kneejerk response, and the phrasing of the question ("turn the default white background black") misleads the intuition, too - it *sounds* like you're saying the <html> element has a white background by default, and so the two code examples are equivalent (just that the first omits a background and so gets the default white), when actually the two examples give the <html> element totally different background declarations.

Sure, getting people's quick intuitions can be useful, but those intuitions can also be *inconsistent*, and it's better for everyone to have a consistent, rational platform even if occasionally corner cases require an "oh, I get it" moment.

If *nothing else*, changing it to ask about `background: transparent` vs `background: white` would at least make the distinction a little clearer and put people in the right mind to think about it, particularly if you also ask to contrast with a `div` with those same declarations.  (The distinction between the element's background and its backdrop isn't always at the top of a person's mind, and the confusing interplay between those two and the "html/body promote their backgrounds to the canvas background" feature just makes it worse.)

**Comment by LeaVerou** [comment] 2018-05-31 08:31
@tabatkins I just copied @smfr's wording. If you have a better wording to suggest that fits in 280 characters, please let me know and I'll post that :)

**Comment by dirkschulze** [comment] 2018-05-31 11:44
@LeaVerou The problem are the details described in https://github.com/w3c/fxtf-drafts/issues/282#issuecomment-385500389

@tabatkins correct me if I am wrong but we had this discussion especially because of `mix-blend-mode` and blending was one of the reasons we differ between the backdrop and `background` property on document root elements.

@mstange I agree that we need to be compatible with `mix-blend-mode`. Especially since `filter` provides blending as well. Either by SVG filter and `<feBlendMode>` filter primitive or by the `background-blur()` filter function in level 2.

**Comment by tabatkins** [comment] 2018-05-31 21:00
Yup, exactly, `mix-blend-mode` prompted us to distinguish the two. There's an opaque colored layer (typically white) *beneath* the root `background`, which isn't associated with any element and can't be affected by anything.

**Comment by AmeliaBR** [comment] 2018-06-05 17:48
Update to the discussion about canvas background colors: apparently Safari under the new OSX dark mode is using a near-black canvas.

(from https://twitter.com/stanton/status/1003971450804555776, and confirmed by various other Twitterers)
![Screenshot of a website in Safari where the background is suddenly dark gray, and the design does not adjust](https://pbs.twimg.com/media/De7SteFWAAArCSO.png)

**Comment by smfr** [comment] 2018-06-13 15:17
Amelia, that's a bug in Safari and is not intentional.

**Comment by smfr** [comment] 2018-06-13 16:40
Proposal: specify in terms of:
Bottom UA-controlled layer which is never affected by CSS.
Intermediate layer which receives the color propagated from the html or body
Filters can affect the intermediate layer, never the bottom layer.

In this model, filters only affect the page background if it's set by the author.

Alternatively, if we specify that the intermediate layer by default has the same color as the bottom layer, then the UA-default background would get affected by filters.

**Comment by chrishtr** [comment] 2018-09-06 03:40
Here is a complete proposal that I think will satisfy the use-cases and is rational:

https://docs.google.com/document/d/1iN0LiaKPF3NZ2PCXD9gdWz1WmruhQIER8fJ_EYMm5YE/edit#

In particular, it will paint the examples given by @smfr the way developers seem to expect.

Also, filters will paint after scrolling, which resolves the main issue left in #11.

**Comment by mstange** [comment] 2018-09-07 00:16
The proposal sounds great to me.

The only thing I'm unsure about is the two mentions of "white" in the Drawing algorithm section. Should both of those be the UI-supplied default background color?

**Comment by svgeesus** [comment] 2018-09-11 17:18
I wasn't sure why the `UA Background Layer` would be white, either.

**Comment by chrishtr** [comment] 2018-09-11 21:17
I used white for two reasons:

1. The de facto state of browsers is that they use a white background
2. To make the explainer easier to read, so white is also a placeholder

Given that filters can have opacity effects which mix with the UA background color, under this proposal, I also think we should consider just specifying that the UA background color must be white. Though I don't know all the history of use cases this might be defeating. Chrome certainly doesn't allow anything other than white, even when there is an installed theme with another color background.

**Comment by karip** [comment] 2018-09-12 06:07
The Compositing and Blending spec says that [the backdrop color](https://www.w3.org/TR/compositing-1/#pagebackdrop) is white. I don't know how normative that is, but you may need to change it.

> "The page group is composited with a backdrop color of white with 100% opacity."

The spec also says that the [order of graphical operations](https://www.w3.org/TR/compositing-1/#compositingandblendingorder) is:

> The compositing model must follow the SVG compositing model (SVG11): first any filter effect is applied, then any clipping, masking, blending and compositing.

This new proposal seems to change the order to blending, filtering and compositing for the root element. How are clipping and masking affected by this change?

**Comment by chrishtr** [comment] 2018-09-12 15:58
> The spec also says that the [order of graphical operations](https://www.w3.org/TR/compositing-1/#compositingandblendingorder) is:
> 
> > The compositing model must follow the SVG compositing model (SVG11): first any filter effect is applied, then any clipping, masking, blending and compositing.

This is fine, we can follow that order. The important thing is to apply after the overflow clip and
scroll of the contents.

Though I'm not sure if masking or css clip can apply to the root element at all.

**Comment by tabatkins** [comment] 2018-09-12 17:02
> I used white for two reasons:
>
> 1. The de facto state of browsers is that they use a white background
> 2. To make the explainer easier to read, so white is also a placeholder

I don't think saying that it composites against opaque white is any simpler than saying it just does against "the backdrop", with a definition that the backdrop is whatever the UA wants it to be (typically transparent for iframes and opaque white for root-level documents, but can be anything). Given that all you're doing with it is compositing over it, the identity of it doesn't matter, and being unnecessarily specific makes it *harder* to read when you actually know the details. ^_^

**Comment by mstange** [comment] 2018-10-20 19:52
For SVG filters on the documentElement we probably also need to define the rectangle that should be used for the filtered element's BBox. I think it would make the most sense to define it to be the viewport rectangle, and *not* the scrolled size of the document. So the following testcase should have a blue fill in the lower half of the viewport at all scroll positions:

```html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<title>The filter should not scroll with the root scroll frame, and the lower half of the viewport should be blue.</title>

<style>
html { filter: url(#filter); }
body { margin: 0; height: 4000px; }
</style>

<body>

<svg height="0">
  <filter id="filter">
    <feFlood flood-color="blue" x="0%" y="50%" width="100%" height="50%" result="blue"/>
    <feMerge>
      <feMergeNode in="SourceGraphic"/>
      <feMergeNode in="blue"/>
    </feMerge>
  </filter>
</svg>

<script>
document.documentElement.scrollTop = 800;
</script>
```

**Comment by chrishtr** [comment] 2018-10-23 20:38
Next step is to apply the relevant updates to each spec based on the resolution. Then will make the change to ship the change in Chromium, file issues against other browsers and close the issue.

**Comment by nickshanks** [comment] 2019-11-29 13:44
I was pointed here in response to a Mozilla bug I filed, and have been reading the comments.

@tabatkins 

> Again, these sorts of polls aren't particularly useful. This isn't something people have thought about before, so you're just getting a kneejerk response

A kneejerk response from folks who haven't thought about this before is very useful, as it illustrates what the web developers intuitivly expect from the web platform. The platform should try to conform to this expecation where it can ("least surprise"), so it is helpful to know what that expectation is.

**Comment by chrishtr** [comment] 2019-12-06 19:15
Implementation tracking bugs:

https://bugs.chromium.org/p/chromium/issues/detail?id=898293
https://bugs.webkit.org/show_bug.cgi?id=204597
https://bugzilla.mozilla.org/show_bug.cgi?id=1599321

**Closed by chrishtr** 2019-12-06 19:15 UTC
Labels: filter-effects-1

**Comment by tabatkins** [comment] 2019-12-06 23:49
> A kneejerk response from folks who haven't thought about this before is very useful, as it illustrates what the web developers intuitivly expect from the web platform. The platform should try to conform to this expecation where it can ("least surprise"), so it is helpful to know what that expectation is.

Sometimes yes, sometimes no. It depends on what's being asked and how it's being asked, and what other factors aren't being mentioned.

Many aspects of the web platform aren't intuitive, or have multiple possible intuitions to go by.  Like I said in the very comment you're responding to:

> Sure, getting people's quick intuitions can be useful, but those intuitions can also be inconsistent, and it's better for everyone to have a consistent, rational platform even if occasionally corner cases require an "oh, I get it" moment.
