### ISSUE TITLE
“ERROR: __clone method called on non-object” 500 response when trying to access specs

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/fxtf-drafts#460] opened 2022-07-12 12:30 UTC
Getting a “ERROR: __clone method called on non-object” 500 errors when trying to access specs” 500 response when trying to access the following specs:

* https://drafts.fxtf.org/css-masking/
* https://drafts.fxtf.org/filter-effects-2/
* https://drafts.fxtf.org/geometry/
* https://drafts.fxtf.org/motion/

However, I can get success responses for the following:

* https://drafts.fxtf.org/compositing/
* https://drafts.fxtf.org/filter-effects/

**Comment by plinss** [comment] 2022-07-12 16:56
This is a dupe of https://github.com/w3c/csswg-drafts/issues/6528 (it's all the same server)

**Closed by plinss** 2022-07-12 16:56 UTC
