### ISSUE TITLE
[motion] CSS and SVG box correspondence seems overly-simplistic

### ISSUE THREAD

**Issue by fantasai** [w3c/fxtf-drafts#66] opened 2016-11-05 01:40 UTC
> For SVG elements without associated CSS layout box, the used value for content-box, padding-box, border-box and margin-box is fill-box.
> 
> For elements with associated CSS layout box, the used value for fill-box, stroke-box and view-box is border-box.

The [Paint module](https://drafts.fxtf.org/paint/#fill-origin) uses a bit more sophistication in its box mappings: content-box | padding-box -> fill-box and border-box -> stroke-box. (The mapping in the other direction relates to text bounds, which is maybe not appropriate here.) At the very least, these two modules should be consistent in how they map the SVG and CSS terms where possible.

**Comment by dbaron** [comment] 2017-04-21 02:12
This should maybe be a duplicate of w3c/csswg-drafts#857.

**Comment by fantasai** [comment] 2018-07-02 00:17
Resolved in https://github.com/w3c/csswg-drafts/issues/857#issuecomment-296024182

**Comment by fantasai** [comment] 2020-01-10 00:23
I've copied out the definitions into the css-box-3 module, since that seems like a useful place to centralize these definitions: https://drafts.csswg.org/css-box-3/

My proposal is that we adopt these definitions in css-box-3 and rebase all the other specs' -box property value definitions over it, then push the spec to CR (dropping `margin-trim` if necessary).

[See also https://github.com/w3c/csswg-drafts/issues/4662 ; I've left the coordinate aspect of the `view-box` definition out until that's resolved.]

**Comment by AmeliaBR** [comment] 2020-03-04 23:57
I agree that it makes sense to define these in a single place & the box model spec makes as much sense as any.

With respect to the definition text:

- The phrases “SVG context” and “CSS context” should be defined.

- It's important to note that some elements (`<svg>` and `<foreignObject>`) can have both SVG and CSS contexts associated with them, for the internal vs external layout systems.  So the fallbacks should be worded as “if this element doesn't have a [CSS|SVG] layout context, use this fallback”.

**Comment by fantasai** [comment] 2020-03-05 00:02
Resolved in https://lists.w3.org/Archives/Public/www-style/2020Feb/0011.html

**Comment by tabatkins** [comment] 2021-05-20 23:26
Partially fixed in <https://github.com/w3c/fxtf-drafts/commit/b0cc95afd8c874aaddb15e99339bd7c7d47ffea3>

**Closed** 2021-05-20 23:56 UTC
Labels: Closed Accepted by WG Resolution, Needs Edits, motion-1
